// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See VSoC.h for the primary calling header

#ifndef VERILATED_VSOC___024ROOT_H_
#define VERILATED_VSOC___024ROOT_H_  // guard

#include "verilated.h"


class VSoC__Syms;

class alignas(VL_CACHE_LINE_BYTES) VSoC___024root final {
  public:

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_IN8(clock,0,0);
        VL_IN8(reset,0,0);
        VL_OUT8(io_uart_tx,0,0);
        VL_IN8(io_uart_rx,0,0);
        CData/*0:0*/ SoC__DOT____Vcellinp__core__io_dcache_stall;
        CData/*0:0*/ SoC__DOT____Vcellinp__dcache__io_mem_valid;
        CData/*0:0*/ SoC__DOT____Vcellinp__uart__io_tx_valid;
        CData/*7:0*/ SoC__DOT____Vcellinp__uart__io_tx_data;
        CData/*0:0*/ SoC__DOT__core__DOT___hazard_io_stall;
        CData/*0:0*/ SoC__DOT__core__DOT___hazard_io_flush;
        CData/*0:0*/ SoC__DOT__core__DOT___writeback_io_wen;
        CData/*0:0*/ SoC__DOT__core__DOT__pipe_stall;
        CData/*0:0*/ SoC__DOT__core__DOT____Vcellinp__forward__io_ex_wen;
        CData/*0:0*/ SoC__DOT__core__DOT____Vcellinp__id_ex__io_flush;
        CData/*0:0*/ SoC__DOT__core__DOT__decode__DOT___GEN;
        CData/*0:0*/ SoC__DOT__core__DOT__regfile__DOT__unnamedblk1__DOT___GEN_0;
        CData/*0:0*/ SoC__DOT__core__DOT__if_id__DOT__reg_valid;
        CData/*4:0*/ SoC__DOT__core__DOT__id_ex__DOT__reg_rd;
        CData/*3:0*/ SoC__DOT__core__DOT__id_ex__DOT__reg_aluOp;
        CData/*2:0*/ SoC__DOT__core__DOT__id_ex__DOT__reg_brOp;
        CData/*2:0*/ SoC__DOT__core__DOT__id_ex__DOT__reg_memOp;
        CData/*0:0*/ SoC__DOT__core__DOT__id_ex__DOT__reg_useImm;
        CData/*0:0*/ SoC__DOT__core__DOT__id_ex__DOT__reg_isLoad;
        CData/*0:0*/ SoC__DOT__core__DOT__id_ex__DOT__reg_isStore;
        CData/*0:0*/ SoC__DOT__core__DOT__id_ex__DOT__reg_isBranch;
        CData/*0:0*/ SoC__DOT__core__DOT__id_ex__DOT__reg_isJal;
        CData/*0:0*/ SoC__DOT__core__DOT__id_ex__DOT__reg_isJalr;
        CData/*0:0*/ SoC__DOT__core__DOT__id_ex__DOT__reg_isLui;
        CData/*0:0*/ SoC__DOT__core__DOT__id_ex__DOT__reg_isAuipc;
        CData/*0:0*/ SoC__DOT__core__DOT__id_ex__DOT__reg_valid;
        CData/*4:0*/ SoC__DOT__core__DOT__ex_mem__DOT__reg_rd;
        CData/*2:0*/ SoC__DOT__core__DOT__ex_mem__DOT__reg_memOp;
        CData/*0:0*/ SoC__DOT__core__DOT__ex_mem__DOT__reg_isLoad;
        CData/*0:0*/ SoC__DOT__core__DOT__ex_mem__DOT__reg_isStore;
        CData/*0:0*/ SoC__DOT__core__DOT__ex_mem__DOT__reg_valid;
        CData/*4:0*/ SoC__DOT__core__DOT__mem_wb__DOT__reg_rd;
        CData/*0:0*/ SoC__DOT__core__DOT__mem_wb__DOT__reg_valid;
        CData/*0:0*/ SoC__DOT__dcache__DOT__valid_0;
        CData/*0:0*/ SoC__DOT__dcache__DOT__valid_1;
        CData/*0:0*/ SoC__DOT__dcache__DOT__valid_2;
        CData/*0:0*/ SoC__DOT__dcache__DOT__valid_3;
        CData/*0:0*/ SoC__DOT__dcache__DOT__valid_4;
        CData/*0:0*/ SoC__DOT__dcache__DOT__valid_5;
        CData/*0:0*/ SoC__DOT__dcache__DOT__valid_6;
        CData/*0:0*/ SoC__DOT__dcache__DOT__valid_7;
        CData/*0:0*/ SoC__DOT__dcache__DOT__valid_8;
        CData/*0:0*/ SoC__DOT__dcache__DOT__valid_9;
        CData/*0:0*/ SoC__DOT__dcache__DOT__valid_10;
        CData/*0:0*/ SoC__DOT__dcache__DOT__valid_11;
        CData/*0:0*/ SoC__DOT__dcache__DOT__valid_12;
        CData/*0:0*/ SoC__DOT__dcache__DOT__valid_13;
        CData/*0:0*/ SoC__DOT__dcache__DOT__valid_14;
        CData/*0:0*/ SoC__DOT__dcache__DOT__valid_15;
        CData/*0:0*/ SoC__DOT__dcache__DOT__valid_16;
        CData/*0:0*/ SoC__DOT__dcache__DOT__valid_17;
        CData/*0:0*/ SoC__DOT__dcache__DOT__valid_18;
        CData/*0:0*/ SoC__DOT__dcache__DOT__valid_19;
        CData/*0:0*/ SoC__DOT__dcache__DOT__valid_20;
        CData/*0:0*/ SoC__DOT__dcache__DOT__valid_21;
        CData/*0:0*/ SoC__DOT__dcache__DOT__valid_22;
        CData/*0:0*/ SoC__DOT__dcache__DOT__valid_23;
        CData/*0:0*/ SoC__DOT__dcache__DOT__valid_24;
        CData/*0:0*/ SoC__DOT__dcache__DOT__valid_25;
        CData/*0:0*/ SoC__DOT__dcache__DOT__valid_26;
    };
    struct {
        CData/*0:0*/ SoC__DOT__dcache__DOT__valid_27;
        CData/*0:0*/ SoC__DOT__dcache__DOT__valid_28;
        CData/*0:0*/ SoC__DOT__dcache__DOT__valid_29;
        CData/*0:0*/ SoC__DOT__dcache__DOT__valid_30;
        CData/*0:0*/ SoC__DOT__dcache__DOT__valid_31;
        CData/*0:0*/ SoC__DOT__dcache__DOT__hit;
        CData/*0:0*/ SoC__DOT__dcache__DOT__unnamedblk1__DOT___GEN_2;
        CData/*0:0*/ SoC__DOT__dcache__DOT__unnamedblk1__DOT___GEN_3;
        CData/*0:0*/ SoC__DOT__dcache__DOT__unnamedblk1__DOT___GEN_4;
        CData/*0:0*/ SoC__DOT__dcache__DOT__unnamedblk1__DOT___GEN_5;
        CData/*0:0*/ SoC__DOT__dcache__DOT__unnamedblk1__DOT___GEN_6;
        CData/*0:0*/ SoC__DOT__dcache__DOT__unnamedblk1__DOT___GEN_7;
        CData/*0:0*/ SoC__DOT__dcache__DOT__unnamedblk1__DOT___GEN_8;
        CData/*0:0*/ SoC__DOT__dcache__DOT__unnamedblk1__DOT___GEN_9;
        CData/*0:0*/ SoC__DOT__dcache__DOT__unnamedblk1__DOT___GEN_10;
        CData/*0:0*/ SoC__DOT__dcache__DOT__unnamedblk1__DOT___GEN_11;
        CData/*0:0*/ SoC__DOT__dcache__DOT__unnamedblk1__DOT___GEN_12;
        CData/*0:0*/ SoC__DOT__dcache__DOT__unnamedblk1__DOT___GEN_13;
        CData/*0:0*/ SoC__DOT__dcache__DOT__unnamedblk1__DOT___GEN_14;
        CData/*0:0*/ SoC__DOT__dcache__DOT__unnamedblk1__DOT___GEN_15;
        CData/*0:0*/ SoC__DOT__dcache__DOT__unnamedblk1__DOT___GEN_16;
        CData/*0:0*/ SoC__DOT__dcache__DOT__unnamedblk1__DOT___GEN_17;
        CData/*0:0*/ SoC__DOT__dcache__DOT__unnamedblk1__DOT___GEN_18;
        CData/*0:0*/ SoC__DOT__dcache__DOT__unnamedblk1__DOT___GEN_19;
        CData/*0:0*/ SoC__DOT__dcache__DOT__unnamedblk1__DOT___GEN_20;
        CData/*0:0*/ SoC__DOT__dcache__DOT__unnamedblk1__DOT___GEN_21;
        CData/*0:0*/ SoC__DOT__dcache__DOT__unnamedblk1__DOT___GEN_22;
        CData/*0:0*/ SoC__DOT__dcache__DOT__unnamedblk1__DOT___GEN_23;
        CData/*0:0*/ SoC__DOT__dcache__DOT__unnamedblk1__DOT___GEN_24;
        CData/*0:0*/ SoC__DOT__dcache__DOT__unnamedblk1__DOT___GEN_25;
        CData/*0:0*/ SoC__DOT__dcache__DOT__unnamedblk1__DOT___GEN_26;
        CData/*0:0*/ SoC__DOT__dcache__DOT__unnamedblk1__DOT___GEN_27;
        CData/*0:0*/ SoC__DOT__dcache__DOT__unnamedblk1__DOT___GEN_28;
        CData/*0:0*/ SoC__DOT__dcache__DOT__unnamedblk1__DOT___GEN_29;
        CData/*0:0*/ SoC__DOT__dcache__DOT__unnamedblk1__DOT___GEN_30;
        CData/*0:0*/ SoC__DOT__dcache__DOT__unnamedblk1__DOT___GEN_31;
        CData/*0:0*/ SoC__DOT__dcache__DOT__unnamedblk1__DOT___GEN_32;
        CData/*0:0*/ SoC__DOT__dcache__DOT__unnamedblk1__DOT___GEN_33;
        CData/*0:0*/ SoC__DOT__dcache__DOT__unnamedblk1__DOT___GEN_34;
        CData/*0:0*/ SoC__DOT__dcache__DOT__unnamedblk1__DOT___GEN_35;
        CData/*0:0*/ SoC__DOT__dcache__DOT__unnamedblk1__DOT___GEN_36;
        CData/*0:0*/ SoC__DOT__dcache__DOT__unnamedblk1__DOT___GEN_37;
        CData/*0:0*/ SoC__DOT__dcache__DOT__unnamedblk1__DOT___GEN_38;
        CData/*0:0*/ SoC__DOT__dcache__DOT__unnamedblk1__DOT___GEN_39;
        CData/*0:0*/ SoC__DOT__dcache__DOT__unnamedblk1__DOT___GEN_40;
        CData/*0:0*/ SoC__DOT__dcache__DOT__unnamedblk1__DOT___GEN_41;
        CData/*0:0*/ SoC__DOT__dcache__DOT__unnamedblk1__DOT___GEN_42;
        CData/*0:0*/ SoC__DOT__dcache__DOT__unnamedblk1__DOT___GEN_43;
        CData/*0:0*/ SoC__DOT__dcache__DOT__unnamedblk1__DOT___GEN_44;
        CData/*0:0*/ SoC__DOT__dcache__DOT__unnamedblk1__DOT___GEN_45;
        CData/*0:0*/ SoC__DOT__dcache__DOT__unnamedblk1__DOT___GEN_46;
        CData/*0:0*/ SoC__DOT__dcache__DOT__unnamedblk1__DOT___GEN_47;
        CData/*0:0*/ SoC__DOT__dcache__DOT__unnamedblk1__DOT___GEN_48;
        CData/*0:0*/ SoC__DOT__dcache__DOT__unnamedblk1__DOT___GEN_49;
        CData/*0:0*/ SoC__DOT__dcache__DOT__unnamedblk1__DOT___GEN_50;
        CData/*0:0*/ SoC__DOT__dcache__DOT__unnamedblk1__DOT___GEN_51;
        CData/*0:0*/ SoC__DOT__dcache__DOT__unnamedblk1__DOT___GEN_52;
        CData/*0:0*/ SoC__DOT__dcache__DOT__unnamedblk1__DOT___GEN_53;
        CData/*0:0*/ SoC__DOT__dcache__DOT__unnamedblk1__DOT___GEN_54;
        CData/*0:0*/ SoC__DOT__dcache__DOT__unnamedblk1__DOT___GEN_55;
        CData/*0:0*/ SoC__DOT__dcache__DOT__unnamedblk1__DOT___GEN_56;
        CData/*0:0*/ SoC__DOT__dcache__DOT__unnamedblk1__DOT___GEN_57;
        CData/*0:0*/ SoC__DOT__dcache__DOT__unnamedblk1__DOT___GEN_58;
        CData/*0:0*/ SoC__DOT__dcache__DOT__unnamedblk1__DOT___GEN_59;
    };
    struct {
        CData/*0:0*/ SoC__DOT__dcache__DOT__unnamedblk1__DOT___GEN_60;
        CData/*0:0*/ SoC__DOT__dcache__DOT__unnamedblk1__DOT___GEN_61;
        CData/*0:0*/ SoC__DOT__dcache__DOT__unnamedblk1__DOT___GEN_62;
        CData/*0:0*/ SoC__DOT__dcache__DOT__unnamedblk1__DOT___GEN_63;
        CData/*0:0*/ SoC__DOT__dcache__DOT__unnamedblk1__DOT___GEN_64;
        CData/*0:0*/ SoC__DOT__dcache__DOT__unnamedblk1__DOT___GEN_65;
        CData/*1:0*/ SoC__DOT__uart__DOT__state;
        CData/*3:0*/ SoC__DOT__uart__DOT__bit_cnt;
        CData/*7:0*/ SoC__DOT__uart__DOT__shift_reg;
        CData/*0:0*/ SoC__DOT__uart__DOT__tx_reg;
        CData/*0:0*/ SoC__DOT__uart__DOT__unnamedblk1__DOT___GEN;
        CData/*0:0*/ SoC__DOT__uart__DOT__unnamedblk1__DOT___GEN_0;
        CData/*0:0*/ SoC__DOT__uart__DOT__unnamedblk1__DOT___GEN_1;
        CData/*0:0*/ SoC__DOT__uart__DOT__unnamedblk1__DOT___GEN_2;
        CData/*7:0*/ SoC__DOT__uart__DOT__unnamedblk1__DOT___GEN_3;
        CData/*0:0*/ SoC__DOT__uart__DOT__unnamedblk1__DOT__unnamedblk2__DOT___GEN_5;
        CData/*0:0*/ SoC__DOT__sram__DOT___GEN;
        CData/*0:0*/ __VdfgRegularize_hebeb780c_0_0;
        CData/*0:0*/ __VdfgRegularize_hebeb780c_0_3;
        CData/*0:0*/ __VdfgRegularize_hebeb780c_0_5;
        CData/*0:0*/ __VdfgRegularize_hebeb780c_0_6;
        CData/*0:0*/ __VdfgRegularize_hebeb780c_0_7;
        CData/*0:0*/ __VdfgRegularize_hebeb780c_0_8;
        CData/*0:0*/ __VdfgRegularize_hebeb780c_0_10;
        CData/*0:0*/ __VdfgRegularize_hebeb780c_0_11;
        CData/*0:0*/ __VdfgRegularize_hebeb780c_0_13;
        CData/*0:0*/ __VdfgRegularize_hebeb780c_0_14;
        CData/*0:0*/ __VstlFirstIteration;
        CData/*0:0*/ __VstlPhaseResult;
        CData/*0:0*/ __Vtrigprevexpr___TOP__clock__0;
        CData/*0:0*/ __VactPhaseResult;
        CData/*0:0*/ __VnbaPhaseResult;
        SData/*8:0*/ SoC__DOT__uart__DOT__baud_cnt;
        QData/*35:0*/ SoC__DOT__uart__DOT__unnamedblk1__DOT___GEN_4;
        IData/*31:0*/ SoC__DOT__core__DOT__if_id__DOT__reg_instr;
        IData/*31:0*/ __VactIterCount;
        QData/*63:0*/ SoC__DOT___sram_io_rdata;
        QData/*63:0*/ SoC__DOT___sram_io_fetch_data;
        QData/*63:0*/ SoC__DOT___core_io_dcache_wdata;
        QData/*63:0*/ SoC__DOT__core__DOT___memory_io_out_result;
        QData/*63:0*/ SoC__DOT__core__DOT___execute_io_out_result;
        QData/*63:0*/ SoC__DOT__core__DOT__frontend__DOT__pc;
        QData/*63:0*/ SoC__DOT__core__DOT__regfile__DOT__regs_0;
        QData/*63:0*/ SoC__DOT__core__DOT__regfile__DOT__regs_1;
        QData/*63:0*/ SoC__DOT__core__DOT__regfile__DOT__regs_2;
        QData/*63:0*/ SoC__DOT__core__DOT__regfile__DOT__regs_3;
        QData/*63:0*/ SoC__DOT__core__DOT__regfile__DOT__regs_4;
        QData/*63:0*/ SoC__DOT__core__DOT__regfile__DOT__regs_5;
        QData/*63:0*/ SoC__DOT__core__DOT__regfile__DOT__regs_6;
        QData/*63:0*/ SoC__DOT__core__DOT__regfile__DOT__regs_7;
        QData/*63:0*/ SoC__DOT__core__DOT__regfile__DOT__regs_8;
        QData/*63:0*/ SoC__DOT__core__DOT__regfile__DOT__regs_9;
        QData/*63:0*/ SoC__DOT__core__DOT__regfile__DOT__regs_10;
        QData/*63:0*/ SoC__DOT__core__DOT__regfile__DOT__regs_11;
        QData/*63:0*/ SoC__DOT__core__DOT__regfile__DOT__regs_12;
        QData/*63:0*/ SoC__DOT__core__DOT__regfile__DOT__regs_13;
        QData/*63:0*/ SoC__DOT__core__DOT__regfile__DOT__regs_14;
        QData/*63:0*/ SoC__DOT__core__DOT__regfile__DOT__regs_15;
        QData/*63:0*/ SoC__DOT__core__DOT__regfile__DOT__regs_16;
        QData/*63:0*/ SoC__DOT__core__DOT__regfile__DOT__regs_17;
        QData/*63:0*/ SoC__DOT__core__DOT__regfile__DOT__regs_18;
        QData/*63:0*/ SoC__DOT__core__DOT__regfile__DOT__regs_19;
        QData/*63:0*/ SoC__DOT__core__DOT__regfile__DOT__regs_20;
        QData/*63:0*/ SoC__DOT__core__DOT__regfile__DOT__regs_21;
    };
    struct {
        QData/*63:0*/ SoC__DOT__core__DOT__regfile__DOT__regs_22;
        QData/*63:0*/ SoC__DOT__core__DOT__regfile__DOT__regs_23;
        QData/*63:0*/ SoC__DOT__core__DOT__regfile__DOT__regs_24;
        QData/*63:0*/ SoC__DOT__core__DOT__regfile__DOT__regs_25;
        QData/*63:0*/ SoC__DOT__core__DOT__regfile__DOT__regs_26;
        QData/*63:0*/ SoC__DOT__core__DOT__regfile__DOT__regs_27;
        QData/*63:0*/ SoC__DOT__core__DOT__regfile__DOT__regs_28;
        QData/*63:0*/ SoC__DOT__core__DOT__regfile__DOT__regs_29;
        QData/*63:0*/ SoC__DOT__core__DOT__regfile__DOT__regs_30;
        QData/*63:0*/ SoC__DOT__core__DOT__regfile__DOT__regs_31;
        VlWide<64>/*2047:0*/ SoC__DOT__core__DOT__regfile__DOT___GEN;
        QData/*63:0*/ SoC__DOT__core__DOT__execute__DOT___bu_io_target;
        QData/*63:0*/ SoC__DOT__core__DOT__if_id__DOT__reg_pc;
        QData/*63:0*/ SoC__DOT__core__DOT__id_ex__DOT__reg_pc;
        QData/*63:0*/ SoC__DOT__core__DOT__id_ex__DOT__reg_rs1_val;
        QData/*63:0*/ SoC__DOT__core__DOT__id_ex__DOT__reg_rs2_val;
        QData/*63:0*/ SoC__DOT__core__DOT__id_ex__DOT__reg_imm;
        QData/*63:0*/ SoC__DOT__core__DOT__ex_mem__DOT__reg_result;
        QData/*63:0*/ SoC__DOT__core__DOT__ex_mem__DOT__reg_rs2_val;
        QData/*63:0*/ SoC__DOT__core__DOT__mem_wb__DOT__reg_result;
        QData/*52:0*/ SoC__DOT__dcache__DOT__tags_0;
        QData/*52:0*/ SoC__DOT__dcache__DOT__tags_1;
        QData/*52:0*/ SoC__DOT__dcache__DOT__tags_2;
        QData/*52:0*/ SoC__DOT__dcache__DOT__tags_3;
        QData/*52:0*/ SoC__DOT__dcache__DOT__tags_4;
        QData/*52:0*/ SoC__DOT__dcache__DOT__tags_5;
        QData/*52:0*/ SoC__DOT__dcache__DOT__tags_6;
        QData/*52:0*/ SoC__DOT__dcache__DOT__tags_7;
        QData/*52:0*/ SoC__DOT__dcache__DOT__tags_8;
        QData/*52:0*/ SoC__DOT__dcache__DOT__tags_9;
        QData/*52:0*/ SoC__DOT__dcache__DOT__tags_10;
        QData/*52:0*/ SoC__DOT__dcache__DOT__tags_11;
        QData/*52:0*/ SoC__DOT__dcache__DOT__tags_12;
        QData/*52:0*/ SoC__DOT__dcache__DOT__tags_13;
        QData/*52:0*/ SoC__DOT__dcache__DOT__tags_14;
        QData/*52:0*/ SoC__DOT__dcache__DOT__tags_15;
        QData/*52:0*/ SoC__DOT__dcache__DOT__tags_16;
        QData/*52:0*/ SoC__DOT__dcache__DOT__tags_17;
        QData/*52:0*/ SoC__DOT__dcache__DOT__tags_18;
        QData/*52:0*/ SoC__DOT__dcache__DOT__tags_19;
        QData/*52:0*/ SoC__DOT__dcache__DOT__tags_20;
        QData/*52:0*/ SoC__DOT__dcache__DOT__tags_21;
        QData/*52:0*/ SoC__DOT__dcache__DOT__tags_22;
        QData/*52:0*/ SoC__DOT__dcache__DOT__tags_23;
        QData/*52:0*/ SoC__DOT__dcache__DOT__tags_24;
        QData/*52:0*/ SoC__DOT__dcache__DOT__tags_25;
        QData/*52:0*/ SoC__DOT__dcache__DOT__tags_26;
        QData/*52:0*/ SoC__DOT__dcache__DOT__tags_27;
        QData/*52:0*/ SoC__DOT__dcache__DOT__tags_28;
        QData/*52:0*/ SoC__DOT__dcache__DOT__tags_29;
        QData/*52:0*/ SoC__DOT__dcache__DOT__tags_30;
        QData/*52:0*/ SoC__DOT__dcache__DOT__tags_31;
        QData/*63:0*/ SoC__DOT__dcache__DOT__data_0;
        QData/*63:0*/ SoC__DOT__dcache__DOT__data_1;
        QData/*63:0*/ SoC__DOT__dcache__DOT__data_2;
        QData/*63:0*/ SoC__DOT__dcache__DOT__data_3;
        QData/*63:0*/ SoC__DOT__dcache__DOT__data_4;
        QData/*63:0*/ SoC__DOT__dcache__DOT__data_5;
        QData/*63:0*/ SoC__DOT__dcache__DOT__data_6;
        QData/*63:0*/ SoC__DOT__dcache__DOT__data_7;
        QData/*63:0*/ SoC__DOT__dcache__DOT__data_8;
        QData/*63:0*/ SoC__DOT__dcache__DOT__data_9;
        QData/*63:0*/ SoC__DOT__dcache__DOT__data_10;
        QData/*63:0*/ SoC__DOT__dcache__DOT__data_11;
    };
    struct {
        QData/*63:0*/ SoC__DOT__dcache__DOT__data_12;
        QData/*63:0*/ SoC__DOT__dcache__DOT__data_13;
        QData/*63:0*/ SoC__DOT__dcache__DOT__data_14;
        QData/*63:0*/ SoC__DOT__dcache__DOT__data_15;
        QData/*63:0*/ SoC__DOT__dcache__DOT__data_16;
        QData/*63:0*/ SoC__DOT__dcache__DOT__data_17;
        QData/*63:0*/ SoC__DOT__dcache__DOT__data_18;
        QData/*63:0*/ SoC__DOT__dcache__DOT__data_19;
        QData/*63:0*/ SoC__DOT__dcache__DOT__data_20;
        QData/*63:0*/ SoC__DOT__dcache__DOT__data_21;
        QData/*63:0*/ SoC__DOT__dcache__DOT__data_22;
        QData/*63:0*/ SoC__DOT__dcache__DOT__data_23;
        QData/*63:0*/ SoC__DOT__dcache__DOT__data_24;
        QData/*63:0*/ SoC__DOT__dcache__DOT__data_25;
        QData/*63:0*/ SoC__DOT__dcache__DOT__data_26;
        QData/*63:0*/ SoC__DOT__dcache__DOT__data_27;
        QData/*63:0*/ SoC__DOT__dcache__DOT__data_28;
        QData/*63:0*/ SoC__DOT__dcache__DOT__data_29;
        QData/*63:0*/ SoC__DOT__dcache__DOT__data_30;
        QData/*63:0*/ SoC__DOT__dcache__DOT__data_31;
        QData/*63:0*/ SoC__DOT__sram__DOT__mergedWord;
        VlUnpacked<QData/*63:0*/, 8192> SoC__DOT__sram__DOT__mem_ext__DOT__Memory;
        VlUnpacked<QData/*63:0*/, 8192> SoC__DOT__sram__DOT__fetch_mem_ext__DOT__Memory;
        VlUnpacked<QData/*63:0*/, 1> __VstlTriggered;
        VlUnpacked<QData/*63:0*/, 1> __VactTriggered;
        VlUnpacked<QData/*63:0*/, 1> __VnbaTriggered;
    };

    // INTERNAL VARIABLES
    VSoC__Syms* vlSymsp;
    const char* vlNamep;

    // CONSTRUCTORS
    VSoC___024root(VSoC__Syms* symsp, const char* namep);
    ~VSoC___024root();
    VL_UNCOPYABLE(VSoC___024root);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
};


#endif  // guard
