// =============================================================================
// AUTO-GENERATED — do not edit by hand
// Source: config/chips/sim.yaml
// Chip:   ValenceSim v0.1.0
// Node:   sky130
// Generated by: scripts/generate_params_master.py
// =============================================================================

package valence.params

object GeneratedParams {

  val physical = PhysicalParams(
    targetNode    = "sky130",
    clockPeriodNs = 10.0,
    setupMarginNs = 0.1,
    holdMarginNs  = 0.05,
    voltageV      = 1.8,
    metalLayers   = 5,
    maxFanout     = 16,
  )

  val iCache = CacheParams(
    nSets       = 32,
    nWays       = 2,
    blockBytes  = 64,
    nMSHRs      = 2,
    nTLBEntries = 16,
  )

  val dCache = CacheParams(
    nSets       = 32,
    nWays       = 2,
    blockBytes  = 64,
    nMSHRs      = 2,
    nTLBEntries = 16,
  )

  val gemm = GEMMParams(
    enabled       = false,
    tileSize      = 4,
    dataWidthBits = 16,
    nMACUnits     = 16,
    scratchpadKB  = 64,
  )

  val core = CoreParams(
    xlen          = 64,
    resetVector   = 0x80000000L,
    nHarts        = 1,
    nStages       = 5,
    hasFPU        = false,
    hasCompressed = false,
    hasAtomic     = false,
    hasVector     = false,
    hasSupervisor = false,
    hasMMU        = false,
    hasPMP        = false,
    iCache        = iCache,
    dCache        = dCache,
    gemm          = gemm,
    physical      = physical,
  )
}