// =============================================================================
// AUTO-GENERATED — do not edit by hand
// Source: config/chips/sky130.yaml
// Chip:   ValenceSky130 v0.1.0
// Node:   sky130
// Generated by: scripts/generate_params_master.py
// =============================================================================

package valence.params

object GeneratedParams {

  val physical = PhysicalParams(
    targetNode    = "sky130",
    clockPeriodNs = 10.0,
    setupMarginNs = 0.1,
    holdMarginNs  = 0.05,
    voltageV      = 1.8,
    metalLayers   = 5,
    maxFanout     = 16,
  )

  val iCache = CacheParams(
    nSets       = 64,
    nWays       = 4,
    blockBytes  = 64,
    nMSHRs      = 4,
    nTLBEntries = 32,
  )

  val dCache = CacheParams(
    nSets       = 64,
    nWays       = 4,
    blockBytes  = 64,
    nMSHRs      = 4,
    nTLBEntries = 32,
  )

  val gemm = GEMMParams(
    enabled       = true,
    tileSize      = 4,
    dataWidthBits = 16,
    nMACUnits     = 16,
    scratchpadKB  = 64,
  )

  val core = CoreParams(
    xlen          = 64,
    resetVector   = 0x80000000L,
    nHarts        = 1,
    nStages       = 5,
    hasFPU        = true,
    hasCompressed = true,
    hasAtomic     = true,
    hasVector     = false,
    hasSupervisor = true,
    hasMMU        = true,
    hasPMP        = true,
    iCache        = iCache,
    dCache        = dCache,
    gemm          = gemm,
    physical      = physical,
  )
}