// =============================================================================
// AUTO-GENERATED — do not edit by hand
// Source: {{ source_file }}
// Chip:   {{ chip.name }} v{{ chip.version }}
// Node:   {{ physical.node }}
// Generated by: scripts/generate_params_master.py
// =============================================================================

package valence.params

object GeneratedParams {

  val physical = PhysicalParams(
    targetNode    = "{{ physical.node }}",
    clockPeriodNs = {{ physical.clock_period_ns }},
    setupMarginNs = {{ physical.setup_margin_ns }},
    holdMarginNs  = {{ physical.hold_margin_ns }},
    voltageV      = {{ physical.voltage_v }},
    metalLayers   = {{ physical.metal_layers }},
    maxFanout     = {{ physical.max_fanout }},
  )

  val iCache = CacheParams(
    nSets       = {{ icache.sets }},
    nWays       = {{ icache.ways }},
    blockBytes  = {{ icache.block_bytes }},
    nMSHRs      = {{ icache.mshrs }},
    nTLBEntries = {{ icache.tlb_entries }},
  )

  val dCache = CacheParams(
    nSets       = {{ dcache.sets }},
    nWays       = {{ dcache.ways }},
    blockBytes  = {{ dcache.block_bytes }},
    nMSHRs      = {{ dcache.mshrs }},
    nTLBEntries = {{ dcache.tlb_entries }},
  )

  val gemm = GEMMParams(
    enabled       = {{ gemm.enabled | lower }},
    tileSize      = {{ gemm.tile_size }},
    dataWidthBits = {{ gemm.data_width }},
    nMACUnits     = {{ gemm.mac_units }},
    scratchpadKB  = {{ gemm.scratchpad_kb }},
  )

  val core = CoreParams(
    xlen          = {{ isa.xlen }},
    resetVector   = {{ pipeline.reset_vector }}L,
    nHarts        = {{ soc.n_harts }},
    nStages       = {{ pipeline.stages }},
    hasFPU        = {{ isa.extensions.fpu | lower }},
    hasCompressed = {{ isa.extensions.compressed | lower }},
    hasAtomic     = {{ isa.extensions.atomic | lower }},
    hasVector     = {{ isa.extensions.vector | lower }},
    hasSupervisor = {{ privilege.supervisor | lower }},
    hasMMU        = {{ privilege.mmu | lower }},
    hasPMP        = {{ privilege.pmp | lower }},
    iCache        = iCache,
    dCache        = dCache,
    gemm          = gemm,
    physical      = physical,
  )
}
